# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Slack Engine
email: web@paul-mesnilgrente.com
description: >-
  You are on the documentation of the rails engine for slack apps.
baseurl: '/slack-engine' # the subpath of your site, e.g. /blog
origin: https://github.com/paul-mesnilgrente/slack-engine
repository: paul-mesnilgrente/slack-engine
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ''
github_username:  'paul-mesnilgrente'

# Build settings
markdown: kramdown
theme: jekyll-theme-time-machine
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections:
  basic_concepts:
    order:
      - listening-to-messages.md
      - sending-messages.md
      - listening-to-events.md
      - using-the-web-api.md
      - listening-to-actions.md
      - responding-to-actions.md
      - acknowledging-events.md
      - listening-and-responding-to-shortcuts.md
      - listening-and-responding-to-commands.md
      - opening-modals.md
      - updating-and-pushing-views.md
      - listening-for-view-submissions.md
      - listening-and-responding-to-options.md

  advanced_concepts:
    order:
      - handling-errors.md
      - authorization.md
      - conversation-stores.md
      - global-middleware.md
      - listener-middleware.md
      - adding-context.md
      - logging.md
      - customizing-a-receiver.md

defaults:
  - scope:
      type: basic_concepts
    values:
      layout: concepts
  - scope:
      type: advanced_concepts
    values:
      layout: concepts
  - scope:
      type: posts
    values:
      layout: posts

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build
  - dist
